import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { FileText } from 'lucide-react';

interface MarkdownReportProps {
  content: string;
  bare?: boolean;
}

const markdownComponents = {
  h1: ({node, ...props}: any) => <h1 className="text-2xl font-bold mb-4 text-slate-900" {...props} />,
  h2: ({node, ...props}: any) => <h2 className="text-xl font-semibold mt-6 mb-3 text-slate-800" {...props} />,
  h3: ({node, ...props}: any) => <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-800" {...props} />,
  ul: ({node, ...props}: any) => <ul className="list-disc pl-5 my-4 space-y-1 text-slate-600" {...props} />,
  ol: ({node, ...props}: any) => <ol className="list-decimal pl-5 my-4 space-y-1 text-slate-600" {...props} />,
  li: ({node, ...props}: any) => <li className="pl-1" {...props} />,
  p: ({node, ...props}: any) => <p className="mb-4 leading-relaxed text-slate-600" {...props} />,
  code: ({node, ...props}: any) => <code className="bg-slate-100 text-slate-800 px-1.5 py-0.5 rounded text-sm font-mono" {...props} />,
  blockquote: ({node, ...props}: any) => <blockquote className="border-l-4 border-primary-200 pl-4 italic text-slate-500 my-4" {...props} />,
  table: ({node, ...props}: any) => (
    <div className="overflow-x-auto my-4">
      <table className="w-full border-collapse text-sm" {...props} />
    </div>
  ),
  thead: ({node, ...props}: any) => <thead className="bg-slate-100" {...props} />,
  th: ({node, ...props}: any) => <th className="border border-slate-200 px-3 py-2 text-left font-semibold text-slate-700" {...props} />,
  td: ({node, ...props}: any) => <td className="border border-slate-200 px-3 py-2 text-slate-600" {...props} />,
  strong: ({node, ...props}: any) => <strong className="font-semibold bg-emerald-50 text-emerald-800 px-1 py-0.5 rounded" {...props} />,
};

export const MarkdownReport: React.FC<MarkdownReportProps> = ({ content, bare = false }) => {
  if (bare) {
    return (
      <div className="prose prose-slate max-w-none prose-headings:font-semibold prose-a:text-primary-600 prose-strong:font-semibold">
        <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
          {content}
        </ReactMarkdown>
      </div>
    );
  }

  return (
    <div className="prose prose-slate max-w-none prose-headings:font-semibold prose-a:text-primary-600 prose-strong:font-semibold">
      <div className="flex items-center gap-2 mb-6 pb-4 border-b border-slate-200">
         <div className="p-2 bg-indigo-50 rounded-lg">
            <FileText className="w-5 h-5 text-indigo-600" />
         </div>
         <div>
             <h3 className="text-lg font-semibold text-slate-900">Agent Report</h3>
             <p className="text-sm text-slate-500">Analysis and cleaning summary generated by Gemini</p>
         </div>
      </div>

      <div className="bg-slate-50/50 rounded-xl p-6 border border-slate-100">
        <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
          {content}
        </ReactMarkdown>
      </div>
    </div>
  );
};
